### ISSUE TITLE
Parameter order

### ISSUE THREAD

**Issue by adon90** [bambish/ScanQLi#10]
Congratulations for your program it is a light sqli scanner that works pretty good, but it has some issues:

- Depending on the order it detects or not, example, vulnerable parameter `id`:
```
python scanqli.py -q -u "http://example.com/details.php?id=12&caca=222" -> Doesn't detect
python scanqli.py -q -u "http://example.com/details.php?caca=222&id=12" -> Detects
```

- Another issue is regarding the -U / --urllist -> it just doesn't detect

- One recommendation is to add more detections on the config.py, for example, I skipped one vulnerable parameter because the MySQL Error was `supplied argument is not a valid MySQL result resource` and that's not included

Thank you very much!

**Comment by bambish** [comment]
Hi,
Thanks for your report.

- With **-q** option ScanQLi just add **'** at the end of the URL. Only the last parameter will affected. I probably will adapt my tool to deal with every parameters.
- Could you show me your command line for the **-U** option? After some test, this option work for me.
- Thanks you for your recommendation. This error message is add in my last commit.
