### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by Phoenix1112** [bambish/ScanQLi#2]
i have this error

Traceback (most recent call last):######################################################]      
  File "./scanqli.py", line 129, in <module>
    result = function.CheckPageListAllVulns(pageset)
  File "/home/CyberTheReapeR/ScanQLi/function.py", line 341, in CheckPageListAllVulns
    payload = CheckPageListVuln(pageset, vuln)
  File "/home/CyberTheReapeR/ScanQLi/function.py", line 319, in CheckPageListVuln
    payload = CheckPageVuln(url, vuln, pageset[url])
  File "/home/CyberTheReapeR/ScanQLi/function.py", line 308, in CheckPageVuln
    postresult = CheckPostVuln(url, vuln, fields, html)
  File "/home/CyberTheReapeR/ScanQLi/function.py", line 272, in CheckPostVuln
    page = PostData(url, payloadeddata)
  File "/home/CyberTheReapeR/ScanQLi/function.py", line 104, in PostData
    r = requests.post(url, data=data, cookies=cookies)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xxx.xxx.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe0aa3bf610>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by bambish** [comment]
Hello,

Thanks for your report.
Could you give me the scanqli command that you have write to get this result please?

**Comment by Phoenix1112** [comment]
İ am using kali linux..

python scanqli.py -u 'https://xxx.xxx.com' -o output.log

**Comment by bambish** [comment]
Try to use the **--wait** option to increase the time between the requests. This error may come from an overly aggressive scan.

I'm going to prevent this error in the code.

**Comment by Phoenix1112** [comment]
Ok i will try iy.. do not close topic

**Comment by Phoenix1112** [comment]
hello... it is working with twitter.com ... but i am trying for dell.com .. same problem..

![Ekran Görüntüsü 2019-05-02 14:27:34](https://user-images.githubusercontent.com/42475284/57072505-9fc0c780-6ce6-11e9-92d0-6c320c0d1549.png)

**Comment by bambish** [comment]
Have you another example of this bug?
I haven't this error even with the same command.

**Be careful**, perform a full scan on dell web site without authorizations is forbidden.
If you stop scanqli scanner before the ------------------- bar appear, it's legal. If you don't stop the scanner after this point, it's illegal and at your own risk.

**Comment by Phoenix1112** [comment]
no .. this is legal... because i am scanning for bug bounty ... now i did change url address. but it is have other error..

![Ekran Görüntüsü 2019-05-02 17:17:57](https://user-images.githubusercontent.com/42475284/57081978-7e6bd580-6cfe-11e9-9213-e8e40d8190dc.png)

**Comment by bambish** [comment]
I have correct this error today. If you make a git clone now this error will disappear.

**Comment by Phoenix1112** [comment]
İ will try 1 hour later... can you make out of band sql scanner program? İ think if you make it , can be run nice with burp suite collaborator.

**Comment by Phoenix1112** [comment]
hello... i did download again... it is worrking now..How does the program respond when a sql vulnerability exists?

example :
sql injection found!

verbose is actve in my command. Will sql give an alert when it finds the error?

**Comment by bambish** [comment]
Like this. The vulns URL are printed with green color and the injection part is printed in red.
If you want more visibility, I recommend you to disable verbose mode. This last print all GET/POST requests. It could be confusing.
![scanqli](https://user-images.githubusercontent.com/37168448/57123039-997f2980-6d80-11e9-8fa2-dc2043ab846e.jpg)

**Comment by Phoenix1112** [comment]
İ understand.. thank you
