### ISSUE TITLE
Fixed IndexError: tuple index out of range

### ISSUE THREAD

**Issue by securiteinfo** [bambish/ScanQLi#3]
python scanqli.py -u 'http://perdu.com/' -r
   ____                   ____    __    _
  / __/ ____ ___ _  ___  / __ \  / /   (_)
 _\ \  / __// _ `/ / _ \/ /_/ / / /__ / /
/___/  \__/ \_,_/ /_//_/\___\_\/____//_/

https://github.com/bambish
https://twitter.com/bambishee

Base URL = http://perdu.com/
1 URLs founds
----------------------------
----------------------------
Traceback (most recent call last):
  File "scanqli.py", line 142, in <module>
    resultlen = numpy.shape(result)[0] * numpy.shape(result)[1]
IndexError: tuple index out of range

**Comment by bambish** [comment]
Hello,
Thanks for your report.

This bug is fixed in my last commit.

**Comment by securiteinfo** [comment]
Thank you very much !
