### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'exceptions.UnboundLocalError' objects

### ISSUE THREAD

**Issue by securiteinfo** [bambish/ScanQLi#4]
Some website generate the following error :

ERROR: Unknow error : GetHTML(): <class 'requests.exceptions.SSLError'>
Traceback (most recent call last):
  File "scanqli.py", line 141, in <module>
    function.PrintError("", error)
  File "/root/ScanQLi/function.py", line 373, in PrintError
    print(colored("ERROR: ", "red", attrs=["bold"]) + colored(command, attrs=["bold"]) + " : " + errormsg)
TypeError: cannot concatenate 'str' and 'exceptions.UnboundLocalError' objects

**Comment by bambish** [comment]
My last commit normally fixed the issue.

**Comment by securiteinfo** [comment]
Thank you !
