### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by securiteinfo** [bambish/ScanQLi#7]
Hello,

I think ScanQLi should work with websites that use self signed certificate or expired certificate (developpement servers for example).

In case of expired certificate we got this error :
ERROR: Connection Error : HTTPSConnectionPool(host='www.xxxxxxxxxxx.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

Can we get a command line switch to ignore certificate verification ?

**Comment by bambish** [comment]
Hello,
Thanks to your report.

You can ignore SSL check with the (new) options **-s** or **--nosslcheck**.

**Comment by securiteinfo** [comment]
Great ! Thank you very much !
